#!/usr/bin/env python3
"""
generate.py — build spread HTML from data instead of hand-authoring it.

Generators (first argument):
  gallery <dir>   One or more photo-grid pages from a folder of images. Chunks the
                  images N-per-page into the .photo-grid component (design.css) and
                  writes a ready-to-wire spread file.

Usage:
  ./book generate gallery assets/trip
  ./book generate gallery assets/trip --per-page 6
  ./book generate gallery assets/trip --out src/spreads/20-trip.html
  ./book generate gallery assets/trip --bg "#111111"

The generated file is a normal spread: nothing about the render/merge pipeline
changes. After generating, add its path to book.spreads in the right position and
run `./book section <name>` to preview.

This is intentionally small and easy to copy: to add a generator (a Markdown
chapter opener, a quote page, a contact sheet), add a `gen_<name>()` that returns
page-HTML strings and register it in GENERATORS.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _build import PROJECT_ROOT, SPREADS_DIR, write  # noqa: E402

IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".tif", ".tiff", ".webp")
GRID_SIZES = (1, 2, 3, 4, 6)


def list_images(dir_rel):
    """Sorted project-relative paths of image files directly in dir_rel."""
    dir_abs = dir_rel if os.path.isabs(dir_rel) else os.path.join(PROJECT_ROOT, dir_rel)
    if not os.path.isdir(dir_abs):
        print(f"Error: not a directory: {dir_rel}")
        sys.exit(1)
    names = sorted(f for f in os.listdir(dir_abs)
                   if f.lower().endswith(IMAGE_EXTS) and not f.startswith("."))
    if not names:
        print(f"Error: no images ({', '.join(IMAGE_EXTS)}) found in {dir_rel}")
        sys.exit(1)
    paths = []
    for n in names:
        abs_p = os.path.join(dir_abs, n)
        rel = os.path.relpath(abs_p, PROJECT_ROOT)
        if rel.startswith(".."):
            print(f"Warning: {rel} is outside the project — WeasyPrint resolves image")
            print(f"         paths from the project root, so move images under assets/.")
        paths.append(rel)
    return paths


def chunk(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def gen_gallery(argv):
    """gallery <dir> [--per-page N] [--out PATH] [--bg COLOR]"""
    opts = {"per_page": 4, "out": None, "bg": "var(--paper, #ffffff)"}
    positional = []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a in ("--per-page", "--out", "--bg"):
            if i + 1 >= len(argv):
                print(f"Error: {a} needs a value")
                sys.exit(1)
            key = a[2:].replace("-", "_")
            val = argv[i + 1]
            opts[key] = int(val) if key == "per_page" else val
            i += 2
        else:
            positional.append(a)
            i += 1
    if not positional:
        print("Error: gallery needs a directory, e.g. ./book generate gallery assets/trip")
        sys.exit(1)
    if opts["per_page"] not in GRID_SIZES:
        print(f"Error: --per-page must be one of {GRID_SIZES}")
        sys.exit(1)

    src_dir = positional[0]
    images = list_images(src_dir)
    name = os.path.basename(os.path.normpath(src_dir)) or "gallery"
    out_rel = opts["out"] or os.path.join(SPREADS_DIR, f"{name}.html")

    pages = list(chunk(images, opts["per_page"]))
    blocks = [
        f"<!-- Generated by `./book generate gallery {src_dir}` — {len(images)} "
        f"images across {len(pages)} page(s). Edit freely; re-running overwrites. -->"
    ]
    for group in pages:
        k = len(group)   # last page may hold fewer; tighten its grid to fit
        cells = "\n".join(
            f'      <div class="photo"><img src="{p}" alt=""></div>' for p in group
        )
        blocks.append(
            f'<div class="page" style="background:{opts["bg"]};">\n'
            f'  <div class="safe">\n'
            f'    <div class="photo-grid grid-{k}">\n{cells}\n    </div>\n'
            f'  </div>\n'
            f'  <span class="page-number center"></span>\n'
            f'</div>'
        )
    write(out_rel, "\n\n".join(blocks) + "\n")

    print(f"Generated {out_rel}")
    print(f"  {len(images)} image(s) → {len(pages)} page(s), {opts['per_page']}/page")
    print(f"  Next: add `{out_rel}` to book.spreads, then `./book section {name}`")


GENERATORS = {"gallery": gen_gallery}


def main():
    argv = sys.argv[1:]
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)
    kind, rest = argv[0], argv[1:]
    if kind not in GENERATORS:
        print(f"Unknown generator: {kind!r}. Available: {', '.join(GENERATORS)}")
        sys.exit(1)
    GENERATORS[kind](rest)


if __name__ == "__main__":
    main()
